### ISSUE TITLE
Paladin: art of war vs exorcism

### ISSUE THREAD

**Issue by dh-harald** [ennvina/spellactivationoverlay#135]
When Art of War procs, it glows the Exorcism spell even if it's on CD. Could you add an extra condition, that checks if exorcism usuable, please?

**Comment by ennvina** [comment]
Hi, late reply here, but I am closing this issue as it is no longer an issue in Cataclysm Classic, because Exorcism now has no cooldown.

For the record, the issue was not fixed because it wasn't easy to add a cooldown condition on top of an aura condition. Prior to version 2.0, effects would be based on either an aura, or a cooldown, but _not_ both.

If the addon should be used again for Wrath in the future, this issue could be fixed easily thanks to development implemented in 2.0.
