### ISSUE TITLE
Frost Spell Alerts are sideways

### ISSUE THREAD

**Issue by ennvina** [ennvina/spellactivationoverlay#250]
Reported by Nemo296 over CurseForge https://legacy.curseforge.com/wow/addons/spellactivationoverlay/#c354

> _Hi, when playing frost mage, the textures are sideways. Example, if the Fingers of Frost procs are suppose to be like this ( ) they're like ⌢ ⌢ and brainfreeze is ( when it's suppose to be ⌢ ._
> _This is not the location, they are in the correct locations, but the textures are rotated._

This is probably due to the texture embedded in Cataclysm game files that has a different rotation than Modern WoW. Rotating the texture CW or CCW should fix it, but it should be done only for Cataclysm.

**Comment by serenity4** [comment]
Hi! Most texture orientations have been fixed by the recent update, but not the `freeze` one (on top when an enemy is frozen): it still shows up in the wrong orientation. What's weird is that in the visual tests (hovering over the spell alert in settings), the texture is oriented properly, but not when triggered by the "enemy frozen" state.

Additionally, I noticed that the `frozen` texture does not show up when enemies are frozen by Improved Cone of Cold, if you happen to have a quick fix in hand. I can file a separate issue otherwise if you prefer.

**Comment by ennvina** [comment]
Hi @serenity4 and thank you for your feedback. Mages will get some love in the next release. Both issues you mentioned will be fixed (among others).

I re-opened this issue because the Freeze debuff texture has wrong orientation, which is exactly the kind of problems pointed out in the original text.
