### ISSUE TITLE
Arcane Missiles

### ISSUE THREAD

**Issue by hoaraucg** [ennvina/spellactivationoverlay#306]
Currently, the Arcane Missiles overlay will disappear while the buff is still active and you are eligible to cast Missiles. This happens most frequently during burn phases where you are going long periods without casting missiles.

**Comment by ennvina** [comment]
Hi and thank you for your feedback. This is a known issue which, after investigation, is caused by the game client.

The game is supposed to send an event called `SPELL_AURA_REFRESH` when an aura is refreshed. For some reason, the game sends it for every spell except Arcane Missiles.

I reported it with the Cataclysm Beta bug report feature. I don't know when Blizzard will fix it (nor do I know if they will even try to fix it).

PS. in the meantime I could write a hack, but considering the addon is undergoing heavy changes, I'd rather not write hacks in the near future.
