### ISSUE TITLE
Issues with new proc 3 Holy power paladin ret

### ISSUE THREAD

**Issue by Lennrj** [ennvina/spellactivationoverlay#308]
I really liked the addition of the 3 holy power proc, however I have a suggestion, when I do 3 holy power the proc appears... but when I left combat it disappears from my screen, even though I keep the 3 holy power, it would be interesting keep the proc on the screen even outside of combat, so that when I start a new combat it starts with the templar's verdict.
![Captura de tela 2024-05-28 221629](https://github.com/ennvina/spellactivationoverlay/assets/112582848/1f5b9ce5-8aa1-484a-8ff2-536c054b241b)

**Comment by Lennrj** [comment]
I really liked the new visual effect you added, congratulations

**Comment by Lennrj** [comment]
I'm really liking the 3 holy power indicator, however when looking for art of war, it seems like it's ahead of the holy power 3 indicator 
![Uploading Captura de tela 2024-05-28 221629.png…]()

**Comment by Lennrj** [comment]
I'm really liking the 3 holy power indicator, however when looking for art of war, it seems like it's ahead of the holy power 3 indicator 
![Captura de tela 2024-05-28 221629](https://github.com/ennvina/spellactivationoverlay/assets/112582848/8596635c-2526-4534-8638-552128170764)

**Comment by ennvina** [comment]
Hi @Lennrj this is a known issue when overlays share the same location. Depending on which one procs first, you may see Art of War slightly better or Holy Power slightly better.

To avoid this, in the previous build I decided to shrink Holy Power. The problem was that I needed to shrink it by a lot (down to 40% of its original size). It was weird to have a tiny overlay next to normal-sized overlays.

So I increased the size of Holy Power, but still smaller of its original size (70%, up from 40%) and slightly avoid conflict. I believe 70% is a good balance of not being too tiny and not conflicting too much.

You can test different sizes by editing source code with a text editor (such as VS Code, Notepad++, or simply Notepad)
1. go to `WoW/Interface/AddOns/SpellActivationOverlay/classes`
2. edit `paladin.lua` with a text editor
3. change scale around line 25, e.g. from `local scale = 0.4 + 0.1*hp; -- 50%, 60%, 70%` to `local scale = 0.3 + 0.1*hp; -- 40%, 50%, 60%` if you want to make it 10% smaller than what it currently is\*
4. save the file and reload your addons (reload UI, or log out and log back in)

\* side note: the text after the double dash `--` is not important. It's called a comment, which only helps developers understanding what the code does. The true formula that matters is the `0.4 + 0.1*hp` which, in this case, roughly means "40% plus 10% per holy power"

**Comment by ennvina** [comment]
Hi, I'm closing this issue, as Holy Power modifications have been released two week ago. If you feel some other equation would be better, feel free to suggest it.
