### ISSUE TITLE
Shaman glowing button problem

### ISSUE THREAD

**Issue by mzokk** [ennvina/spellactivationoverlay#59]
Maelstrom Weapon proc 0 glowing effect.
Here is the file with changes https://pastebin.com/xVSsDXeN

**Comment by ennvina** [comment]
Hi and thank you for your feedback.

First of all, Maelstrom Weapon affects Hex since patch 3.2.0 and onwards. Because Wrath Classic is based on patch 3.3.5, Hex should be added too.

When there are too many buttons to glow, it becomes difficult to make a choice. The rule of thumb is:
- 1 glowing button is ideal
- 2 glowing buttons is good
- 3 glowing buttons is okay-ish
- 4 buttons or more is too much

Because Maelstrom Weapon triggers up to 6 different spells, it falls into the "too many buttons" category.

In the future, there will be options to select glowing buttons individually, cf #61. Maelstrom Weapon will most likely have options for this.

**Comment by ennvina** [comment]
Because #61 has been implemented, it is now possible to make spells glow with 5 stacks of Maelstrom Weapon.

Please note, buttons will not glow with 1-4 stacks.
