### ISSUE TITLE
[Demo Warlock] Decimation

### ISSUE THREAD

**Issue by Glandaaalf** [ennvina/spellactivationoverlay#71]
Hi there,

it would be a great addition to have visual procs for Decimation (the demo warlock execute phase).
It's also easy as it's a buff.

Thanks for your work and contribution :)

**Comment by ennvina** [comment]
Hi and thank you for your feedback.

An issue already exists for Decimation 👉 #50

You probably did not see it because it was recently addressed, which means:
- the issue was closed, so you have missed it (by default, github hides closed issues)
- you still couldn’t enjoy it, because it was not officially released yet

You’ll be pleased to know it made it to the latest release 👉 [v0.6.3](https://github.com/ennvina/spellactivationoverlay/releases/tag/v0.6.3)

**Comment by Glandaaalf** [comment]
Oh, just got this update, this is awesome!!
